version: "3.3"
services:
  http:
    build: ./http
    ports:
      - "8080:80"
  minecraft:
    image: itzg/minecraft-server:java11
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: SPIGOT
      VERSION: 1.16.4
      GAMEMODE: survival
      DIFFICULTY: normal
  discord:
    build: ./discord
  media:
    image: linuxserver/jellyfin
    volumes:
      - ./media/shows:/data/tvshows
      - ./media/movies:/data/movies
