version: "3.3"

secrets:
  musicbot:
    file: ./secrets/musicbot/config.txt
  discord:
    file: ./secrets/discord/config.json

services:
  http:
    build: ./http
    ports:
      - "8080:80"

  minecraft:
    image: itzg/minecraft-server:java11
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      JVM_OPTS: "-DIReallyKnowWhatIAmDoingISwear=true"
      MEMORY: 2G
      TYPE: SPIGOT
      VERSION: 1.16.5
      GAMEMODE: survival
      DIFFICULTY: normal
      EXTRA_ARGS: "--world-dir ./worlds/"
    volumes:
      - ./minecraft/server:/data

  discord:
    build: ./discord
    environment:
      CRED_FILE: /run/secrets/discord
    secrets:
      - discord

  musicbot:
    build: ./musicbot
    environment:
      CRED_FILE: /run/secrets/musicbot
    secrets:
      - musicbot

  media:
    image: linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - JELLYFIN_PublishedServerUrl=media.skyspa.net
    volumes:
      - ./media/config:/config
      - ./media/shows:/data/tvshows
      - ./media/movies:/data/movies
    ports:
      - 8096:8096 #http
      - 8920:8920 #https
      - 7359:7359/udp #auto-discovery
      - 1900:1900/udp #auto-discovery
    restart: unless-stopped
